export const UI_ROUTES = {
  dashboard: '/',
  login: 'Login',
  forgotPassword: 'ForgotPassword',
  authenticated: 'Authenticated',
  courses: 'Courses',
  profile: 'Profile',
  editProfile: 'EditProfile',
  settings: 'Settings',
  categoryWiseCourses: 'CategoryWiseCourses',
  profileSection: 'ProfileSection',
  filterWiseCourses: 'FilterWiseCourses',
  groupsListing: 'GroupsListing',
  groupDetail: 'GroupDetail',
  chatList: 'ChatList',
  chatScreen: 'ChatScreen',
  myCourseList: 'MyCourseList',
  courseDetail: 'CourseDetail',
  calender: 'Calender',
  lessionWiseTopics: 'LessionWiseTopics',
  groupDiscussions: 'GroupDiscussions',
  commentSection: 'CommentSection',
  quizStartPage: 'QuizStartPage',
  quizPlay: 'QuizPlay',
  quizSubmit: 'QuizSubmit',
  lessionDetail: 'LessionDetail',
  quizStatictics:'QuizStatictics',
};

export const navigateTo = route => `/${route}`;
